### PR TITLE
Remove Contractor and re-organize

### PR DESCRIPTION
**Pull request by danirabbit**
AFAIK, it's not possible for Flatpak apps to read contract files, so this is kind of irrelevant now

Also removed the "Desktop Integration" page since it's mainly fluff

### CODE REVIEW

**Comment by cassidyjames** [comment]
@danrabbit can Flatpak apps still provide Contracts, though, e.g. so they show up in Files or Code? If not, do we have a recommended replacement for that?

I guess this and #34 also raises the question: is the HIG only for third-party developers? If so, how/where should we document best practices for first-party things?

**Comment by danrabbit** [comment]
@cassidyjames AFAIK, no they can't. The replacement is to pursue adding a mediatype parameter to the app launcher actions spec. But apps in Flatpak can't even list other apps for like an "Open With" menu. So we need some kind of portal with a share sheet type of thing to even have that functionality.

Since the plan is to Flatpak All The Things, we'll have to deal with these same issues in our first party apps as well, so I'm not sure there's really a strong distinction there

**Comment by hanaral** [comment]
I'd like to note that many apps such as code (assuming it will be flatpak'ed) have context menu items for 'Open in X', so whatever it is replaced with needs to be just as intuitive and performant. There is also the worry that it will place a barrier for quickly judging which type of app can open an item, since it will be another layer of interface before you can see what's available.
[I've opened a relevant issue regarding this problem under settings daemon](https://github.com/elementary/settings-daemon/issues/28)

**Comment by Marukesu** [comment]
> AFAIK, it's not possible for Flatpak apps to read contract files, so this is kind of irrelevant now

Well, they can, they only need to add `--talk-name=org.elementary.Contractor` to finish args.

We can also add a portal to copy the sandboxed contract to the host path so they can be used on others apps.

**Pull request merged**
